### ISSUE TITLE
Add support for u8 raw file output

### ISSUE THREAD

**Issue by andimik** [Opendigitalradio/ODR-DabMod#14]
In (closed) #13 I learned that u8 is the input for qt-dab and welle.io whereas ODR-DabMod exports s8 as raw format.

Would it be possible to add u8 format for export?

That would then allow the authors (Jan and Albrecht) to test their programs directly with raw file generated from eti-streams (made by dabtools or by eti-stuff), thus reduces the internet traffic (currently I have to send them SDR or RAW files).

**Comment by mpbraendli** [comment]
Yes, good idea!

**Comment by mpbraendli** [comment]
Added in commit 30b6ffb8afae8aee5bfc2f92d704202635bc7f3b in the next branch.
Thanks for the suggestion!
