### ISSUE TITLE
Command line parameter for selecting IQ samples format

### ISSUE THREAD

**Issue by lars18th** [Opendigitalradio/ODR-DabMod#19]
Hi,

I suggest to add one new command-line parameter for selecting the I/Q samples format, as it can be done in the configuration file: `--format=complexf,complexf_normalisex,s8,u8`.

I know, this can be done using the configuratin file. However this will simplify to interoperate with other tools that read IQ samples and needs only to use the regular command-line parameters (instead of a complex conf file).

You agree?

**Comment by mpbraendli** [comment]
Yeah, makes sense. Added in 0a07b6c

**Comment by lars18th** [comment]
> Yeah, makes sense. Added in 0a07b6c

Great! Thank you! :smile:
