### ISSUE TITLE
Wrong display in telnet header

### ISSUE THREAD

**Issue by YoannQueret** [Opendigitalradio/ODR-DabMod#21]
When connect with telnet to RC, the header display "ODR-DabMux" but it's the RC for ODR-DabMod

```
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
ODR-DabMux Remote Control CLI
Write 'help' for help.
**********
```

**Comment by YoannQueret** [comment]
You're right @rashuk 
it's corrected in Next branch/
[Fix telnet RC welcome string](https://github.com/Opendigitalradio/ODR-DabMod/commit/aa55134b32e8026ad0e052717f488a7e0837bda5)

**Comment by mpbraendli** [comment]
Every year I fix this again at RadioHack :-)
