### ISSUE TITLE
zmqctrlendpoint not support hostname.

### ISSUE THREAD

**Issue by YoannQueret** [Opendigitalradio/ODR-DabMod#29]
zmqctrlendpoint not support hostname.

Can not use : 
zmqctrlendpoint: tcp://localhost:9400
But need to put IP :
zmqctrlendpoint: tcp://127.0.0.1:9400

/etc/hosts file is correct :
127.0.0.1	localhost

**Comment by mpbraendli** [comment]
`zmq_bind()` expects `tcp://<interface>:<port>` so maybe `tcp://lo:9400` would work. Can you confirm?

But I agree that the `example.ini` is misleading, I will fix this.

**Comment by YoannQueret** [comment]
I confirm !
Can put iface or ip address, but not hostname.
