### ISSUE TITLE
EEP b protection levels

### ISSUE THREAD

**Issue by ashelford** [Opendigitalradio/ODR-DabMod#31]
Greetings from Portsmouth.

I want to operate a DAB+ service at 64kbps EEP2b. I know that typing 2 as the protection level defaults to EEP2a. Typing 2b does not seem to work however. Are EEP1b/2b/3b/4b supported? If they are supported can anyone tell me what I am doing wrong please?

Many thanks,

Ash

**Comment by rashuk** [comment]
Hi Ash.

You need to have the following in the appropriate sub-channel section of
your multiplex configuration file:

protection-profile EEP_B
protection 2

Best regards,

Rash.
