### ISSUE TITLE
Output file s16 seems corrupt

### ISSUE THREAD

**Issue by F5OEO** [Opendigitalradio/ODR-DabMod#32]
Maybe a misunderstanding, but output 16bit file(should be litlle endian) seems to be without negative value.

Here is the result of samples : 
First 2 lines : I/Q signed int 16bits (s16 format)
Next 2 lines : I/Q signed 8 (s8 format)

Note : running on Raspberry

[
![dab16bits](https://user-images.githubusercontent.com/6190918/49582415-3fa34080-f955-11e8-8446-df7924a6d91f.png)
](url)

**Comment by rashuk** [comment]
Hi Evariste! ;)

Is mentioning that the other output (other than s8) are 32-bit complex
floats useful?

R.

**Comment by F5OEO** [comment]
Thanks Rash, I better understand. On LimeSDR, to have less USB bandwidth, it should be better to have s16 iq instead of real. I will translate it on dabmod side or Limesdrsend.

**Comment by mpbraendli** [comment]
Bonjour Evariste,

That looks wrong indeed. I guess (from your screenshot) that you opened it in audacity, so I tried the same (Raw import, signed 16-bits, little-endian, stereo, 2048Hz)
![image](https://user-images.githubusercontent.com/5902825/49652815-6afc5d00-fa33-11e8-971f-8c3c16ffa7d4.png)

Length seems correct too.

Do you think the format converter does something wrong on 32-bit systems or on ARM?

https://github.com/Opendigitalradio/ODR-DabMod/blob/master/src/FormatConverter.cpp#L55

PS:
The SoapySDR API also presents options for over-the-wire format, maybe that's an easy way to reduce bandwidth.

**Comment by F5OEO** [comment]
Replace https://github.com/Opendigitalradio/ODR-DabMod/blob/5bb71419937a4d8919ef33df088f73e6c705b028/src/FormatConverter.cpp#L57
by
  int16_t* out = reinterpret_cast<int16_t*>(dataOut->getData());

Works OK now !

**Comment by mpbraendli** [comment]
![facepalm](https://media.giphy.com/media/3otPotnGlA5FSF2fKw/giphy.gif)

But why did it work here?!?

Anyway, fixed in 5d825e7

**Comment by rashuk** [comment]
This explains a few things...and a few very long, non-productive days...

Thanks! :-D
