### ISSUE TITLE
DC spike

### ISSUE THREAD

**Issue by andimik** [Opendigitalradio/ODR-DabMod#51]
It seems that ODR-DabMod generates a DC Spike when the digital amplitude gain is set much smaller than 1.

![grafik](https://user-images.githubusercontent.com/24510556/179847848-260c7cf6-4cba-4c03-9052-3418c206a00e.png)
![grafik](https://user-images.githubusercontent.com/24510556/179848342-ae0a3da7-e7ca-4a2c-ae0d-d2e3b132a75f.png)

This was created with

```
odr-dabmod ./foo.eti -f ./foo.raw -F u8 -a 0.2
```

Is this normal?

Without the `-a` parameter it looks as expected:

![grafik](https://user-images.githubusercontent.com/24510556/179849207-04bdbaa8-e10d-479f-928b-e372934b1ba3.png)
![grafik](https://user-images.githubusercontent.com/24510556/179849259-0cb545b3-a4bb-4a32-aeeb-0e1190dfb83c.png)

**Comment by mpbraendli** [comment]
Mmh, maybe it's related to the u8 output. Inside `FormatConverter.cpp`, can you try with `+127` on line 68? Maybe that's off by one.

**Comment by andimik** [comment]
No, it's larger than before ...
![grafik](https://user-images.githubusercontent.com/24510556/180382436-b0af75a1-81ff-4b0d-a106-e7b9b58fbb0f.png)

**Comment by andimik** [comment]
BTW: s8 and s16 show both the same spike, but into the other direction

# s8

![grafik](https://user-images.githubusercontent.com/24510556/180387450-aab1dbb6-b5c8-47ec-be3f-658e2993519e.png)

# s16be

![grafik](https://user-images.githubusercontent.com/24510556/180388084-b6512ab1-9832-43ae-8b0f-a4b130ece881.png)

Please mind the y axis. I don't know if this is an issue with `welle-io` or with `odr-dabmod`

**Comment by mpbraendli** [comment]
The plots for s8 and s16be look good, the central carrier is not supposed to have any energy.

For u8, it would be great it you could measure the average value of I and Q over a complete transmission frame. For example with numpy. You can easily load complex float data like that:

```python
import numpy
frame = numpy.fromfile("your_file.iq.cf32", numpy.complex64)
```

Maybe it's not as easy with interleaved u8 I/Q, let me know if you want to do this and if you're stuck somewhere.

And then use [numpy.average](https://numpy.org/doc/stable/reference/generated/numpy.average.html) on the `frame`.

**Comment by andimik** [comment]
Do you fear it's related to my PC? If not I would like you (or someone else) to measure that.

**Comment by mpbraendli** [comment]
No I don't think so. I would just prefer not doing it myself :-)

**Comment by mpbraendli** [comment]
I don't think we're going to investigate this further, and since I believe it is more a consequence of the u8 representation rather than a real issue I'll close this ticket.
