### ISSUE TITLE
ZeroMQ input removed?

### ISSUE THREAD

**Issue by andimik** [Opendigitalradio/ODR-DabMod#56]
Although I have configured with ZeroMQ input, this seems to be no longer working.

```
$ odr-dabmod zmq+tcp://IP-ADDRESS -f /tmp/test.raw -F u8
ODR-DabMod version v2.6.0-71-g03bf901, compiled at Mar 11 2024, 21:11:40
Compiled with features: zeromq output_soapysdr SSE 
Modulator runtime error: Support for ZeroMQ input transport has been removed.
```

But the help still shows it:

```
$ ./configure --help | grep zero
  --disable-zeromq        Disable ZeroMQ input, output and remote control
```

I have seen that the commit was 0aec6da11b4add62ac473e3f4ea813bb4a8a556d But I don't understand why this has been removed.

I'm back to `ODR-DabMod version v2.6.0-2-g0f86d69` (0f86d69), where it is working.

**Comment by mpbraendli** [comment]
Hi, I removed it because I didn't want to maintain that anymore.

The configure flag still exists because the RC and zmq output are still here.
