### ISSUE TITLE
sse with gcc 4.9.2

### ISSUE THREAD

**Issue by Hoernchen** [Opendigitalradio/ODR-DabMod#9]
Building with gcc 4.9.2 fails because the sse check doesn't work, see https://bugzilla.redhat.com/show_bug.cgi?id=1092991#c1 for an explanation. Adding CFLAGS="-msse2" to configure.ac before the sse test runs fixes this for me.

**Comment by mpbraendli** [comment]
I have been compiling ODR-DabMod with GCC 4.9.2 for some time now. On this machine the -msse and -msse2 flags are correctly defined by the autotools.

What distribution are you on ? (maybe I can reproduce)

using gcc (GCC) 4.9.2 20150304

**Comment by mpbraendli** [comment]
Maybe it would be better to replace the ad-hoc check by http://www.gnu.org/software/autoconf-archive/ax_ext.html

I will look into this solution.

**Comment by Hoernchen** [comment]
*cough* msys2/mingw32, I was curious if I'd get it to build. (The answer is yes.)

**Comment by mpbraendli** [comment]
I have taken as an action to improve for the autoconf check.

I'm not sure cygwin and it's silblings is a target we want to support, but it would be nice if it would work.
